### ISSUE TITLE
Makes sound for every request and not just google

### ISSUE THREAD

**Issue by jonas-w** [berthubert/googerteller#12]
I executed the command with "| tee >(./teller)" to also see for what requests it makes a sound.
And many ARP requests showed up, that's why it constantly made a sound.

I also don't understand the "dst net 192.x.x.x/32" part, why would we need that?. This is probably the reason why it also includes local traffic.

**Comment by jonas-w** [comment]
Tried removing the first bit with "dst net 192.x.x.x/32" and now it seems to be working!

**Comment by mechanyx** [comment]
Same issue. I have a very locked down system and so I ran tee to stderr and saw a lot of local arp traffic that I don't think has anything to do with Google.

I had to do more than simply remove the first bit with "dst net 192.x.x.x/32" because the following shell expression with the rest of the filter starts with "or" and you can't start the tcpdump filter with "or" so you need to either alter the shell expression to not emit the first "or" or you need to put a valid filter rule in place of the 192 part. I did the latter by just pulling the first line out of the prefixs file:

sudo tcpdump -n -l dst net 8.8.4.0/24 $(for a in $(cat goog-prefixes.txt); do echo or dst net $a; done)

**Comment by jonas-w** [comment]
Sorry should have explained this part more.
I printed the while loop to a file and removed the first "or".

I don't know if there is a more elegant solution but this was a quick hack to make it work for me.

**Comment by jonas-w** [comment]
Seems like @berthubert "fixed" it. If the IP in the command in the readme isn't in your subnet then it will work as intended.

**Comment by jonas-w** [comment]
I'm closing this, as @berthubert created a better way of logging this, with iptables!
